-- CREATE EXTENSION IF NOT EXISTS postgres_fdw;

--CREATE SERVER source_server FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host 'atl-datamart_data-warehouse_1', dbname 'nyc_warehouse', port '5432');

--CREATE USER MAPPING FOR admin SERVER source_server OPTIONS (user 'admin', password 'admin');

--CREATE FOREIGN TABLE foreign_table ( vendorid int4 NULL, tpep_pickup_datetime timestamp NULL, tpep_dropoff_datetime timestamp NULL, passenger_count float8 NULL, trip_distance float8 NULL, ratecodeid float8 NULL, store_and_fwd_flag text NULL, pulocationid int4 NULL, dolocationid int4 NULL, payment_type int8 NULL, fare_amount float8 NULL, extra float8 NULL, mta_tax float8 NULL, tip_amount float8 NULL, tolls_amount float8 NULL, improvement_surcharge float8 NULL, total_amount float8 NULL, congestion_surcharge float8 NULL, airport_fee float8 NULL ) SERVER source_server OPTIONS (schema_name 'public', table_name 'nyc_raw');


CREATE TABLE "dim_vendor" (
	"vendor_id" INT UNIQUE,
	"vendor_name" VARCHAR,
	PRIMARY KEY("vendor_id")
);

CREATE TABLE "dim_rate_code" (
	"rate_code_id" INT UNIQUE,
	"rate_description" VARCHAR,
	PRIMARY KEY("rate_code_id")
);

CREATE TABLE "dim_payment_type" (
	"payment_type_id" INT UNIQUE,
	"payment_description" VARCHAR,
	PRIMARY KEY("payment_type_id")
);

CREATE TABLE "dim_location" (
	"location_id" INT UNIQUE,
	"location_description" VARCHAR,
	PRIMARY KEY("location_id")
);

CREATE TABLE "dim_datetime" (
	"datetime_id" INT unique GENERATED BY DEFAULT AS IDENTITY,
	"pickup_datetime" TIMESTAMP,
	"dropoff_datetime" TIMESTAMP,
	PRIMARY KEY("datetime_id")
);

CREATE TABLE "fact_trips" (
	"trip_id" INT UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"vendor_id" INT,
	"rate_code_id" INT,
	"payment_type_id" INT,
	"pickup_location_id" INT,
	"dropoff_location_id" INT,
	"datetime_id" INT,
	"passenger_count" INT,
	"trip_distance" FLOAT,
	"fare_amount" FLOAT,
	"extra" FLOAT,
	"mta_tax" FLOAT,
	"tip_amount" FLOAT,
	"tolls_amount" FLOAT,
	"improvement_surcharge" FLOAT,
	"total_amount" FLOAT,
	"congestion_surcharge" FLOAT,
	"airport_fee" FLOAT,
	"store_and_fwd_flag" CHAR(1),
	PRIMARY KEY("trip_id"),
    FOREIGN KEY (vendor_id) REFERENCES dim_vendor(vendor_id),
    FOREIGN KEY (rate_code_id) REFERENCES dim_rate_code(rate_code_id),
    FOREIGN KEY (payment_type_id) REFERENCES dim_payment_type(payment_type_id),
    FOREIGN KEY (pickup_location_id) REFERENCES dim_location(location_id),
    FOREIGN KEY (dropoff_location_id) REFERENCES dim_location(location_id),
    FOREIGN KEY (datetime_id) REFERENCES dim_datetime(datetime_id)
);